In [1]:
import pandas as pd

In [6]:
can_lang = pd.read_csv("D:/Data/Git/dsci-100-student-python/materials/py_tutorial_classification1/data/can_lang.csv")

In [7]:
can_lang.head()

,category,language,mother_tongue,most_at_home,most_at_work,lang_known
0,Aboriginal languages,"Aboriginal languages, n.o.s.",590,235,30,665
1,Non-Official & Non-Aboriginal languages,Afrikaans,10260,4785,85,23415
2,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",1150,445,10,2775
3,Non-Official & Non-Aboriginal languages,Akan (Twi),13460,5985,25,22150
4,Non-Official & Non-Aboriginal languages,Albanian,26895,13135,345,31930

In [ ]:
# Select only the rows where the category is "Aboriginal languages"
can_lang[can_lang['category'] == "Aboriginal languages"]
# select only the language and mother tongue columns "
can_lang[["language", "mother_tongue"]]

                           language  mother_tongue
0      Aboriginal languages, n.o.s.            590
1                         Afrikaans          10260
2    Afro-Asiatic languages, n.i.e.           1150
3                        Akan (Twi)          13460
4                          Albanian          26895
..                              ...            ...
209                           Wolof           3990
210                      Woods Cree           1840
211               Wu (Shanghainese)          12915
212                         Yiddish          13555
213                          Yoruba           9080

[214 rows x 2 columns]

In [22]:
# use .loc to filter rows and columns at the same time
aboriginal_lang = can_lang.loc[can_lang['category'] == "Aboriginal languages", ["language", "mother_tongue"]]

arranged_lang  = aboriginal_lang.sort_values("mother_tongue", ascending=False)
ten_lang = arranged_lang.head(10).copy()
ten_lang

              language  mother_tongue
40        Cree, n.o.s.          64050
89           Inuktitut          35210
138            Ojibway          17885
137           Oji-Cree          12855
48                Dene          10700
125  Montagnais (Innu)          10235
119            Mi'kmaq           6690
13           Atikamekw           6150
149        Plains Cree           3065
180             Stoney           3025

In [24]:
canadian_population = can_lang["mother_tongue"].sum()
canadian_population
ten_lang["percent_mother_tongue"] = ten_lang["mother_tongue"] / canadian_population * 100
ten_lang

              language  mother_tongue  percent_mother_tongue
40        Cree, n.o.s.          64050               0.188668
89           Inuktitut          35210               0.103716
138            Ojibway          17885               0.052683
137           Oji-Cree          12855               0.037866
48                Dene          10700               0.031518
125  Montagnais (Innu)          10235               0.030149
119            Mi'kmaq           6690               0.019706
13           Atikamekw           6150               0.018116
149        Plains Cree           3065               0.009028
180             Stoney           3025               0.008911

In [ ]:
bar_chart = ten_lang.plot.bar(x="language", y="percent_mother_tongue", legend=False)